# Quarternions via complex matrices

## The basics

In [ ]:
"""
The below are some functions that naively perform some basic calculations with quarternions. Just as complex numbers 
can be thought of as a 'doubled up' version of the real numbers with operations like multiplication and addition that
are consistent with the real ones, so it is that quarternions can be viewed as a 'doubled up' version of the complex
numbers with operations like multiplication and addition that are consistent with the complex ones. More details can be
found here:

https://mathworld.wolfram.com/Quaternion.html

In this notebook we will perform these calculations approaching quarternions and 2x2 complex matrices. The result is a 
series of functions that are much simpler than their naive counterparts whilst repeatedly using the sledgehammer of
numpy.


In each of the below functions the quarternion a+bi+cj+dk is entered as the list [a, b, c, d].
"""

In [17]:
# A function for converting a quarternion to a complex matrix.

import numpy as np

def quart_mat(in1):
    a, b, c, d = in1[0], in1[1], in1[2], in1[3]
    return np.array([[a+b*1j, c+d*1j], [-c+d*1j, a-b*1j]])

In [18]:
# An example of the above

quart_mat([1, 2, 3, 4])

array([[ 1.+2.j,  3.+4.j],
       [-3.+4.j,  1.-2.j]])

In [24]:
# A function for conjugating a quarternion expressing the result as a matrix.

def quart_conj_mat(in1):
    return quart_mat([in1[0], -in1[1], -in1[2], -in1[3]])  

In [25]:
# An example of the above

quart_conj_mat([1, 2, 3, 4])

array([[ 1.-2.j, -3.-4.j],
       [ 3.-4.j,  1.+2.j]])

In [34]:
# A function for calculating the sum of two quarternions and expressing the result as a matrix.

def quart_sum_mat(in1, in2):
    return quart_mat(in1) + quart_mat(in2)

In [35]:
# An example of the above

quart_sum_mat([1,2,3,4], [2,3,5,-7])

array([[ 3.+5.j,  8.-3.j],
       [-8.-3.j,  3.-5.j]])

In [36]:
# A function for calculating the difference of two quarternions and expressing the result as a matrix.

def quart_diff_mat(in1, in2):
    return quart_mat(in1) - quart_mat(in2)

In [37]:
# An example of the above

quart_diff_mat([1,2,3,4], [2,3,5,-7])

array([[-1. -1.j, -2.+11.j],
       [ 2.+11.j, -1. +1.j]])

## Multiplication and division

In [33]:
import warnings
warnings.filterwarnings("default", category=DeprecationWarning)

In [42]:
# A function for calculating the norm of a quarternion via matrices

def quart_norm_mat(in1):
    return np.sqrt(np.linalg.det(quart_mat(in1))).real

In [43]:
# An example of the above

quart_norm_mat([2, 2, 1, 4])

5.0

In [44]:
# A function for calculating the product of two quarternions as matrices.

def quart_prod_mat(in1, in2):
    return quart_mat(in1) @ quart_mat(in2)

In [45]:
# An example of the above

quart_prod_mat([1, 2, 3, 4], [4, -3, 2, -1])

array([[ 8. -6.j,  4.+28.j],
       [-4.+28.j,  8. +6.j]])

In [46]:
# A function for calculating the multiplicative inverse of a quarternion as matrices

def quart_inv_mat(in1):
    if in1 == [0,0,0,0]:
        print("The quarternion is 0 and therefore not invertible!")
    else:
        return quart_conj_mat(in1) / quart_norm_mat(in1)

In [47]:
# An example of the above

quart_inv_mat([2, 2, 1, 4])

array([[ 0.4-0.4j, -0.2-0.8j],
       [ 0.2-0.8j,  0.4+0.4j]])

In [48]:
quart_inv_mat([0,0,0,0])

The quarternion is 0 and therefore not invertible!
